---
sites:
  - EU-WEST:
      type: area
      name: EU-WEST
      parentName: Global
  - FRA:
      type: area
      name: FRA
      parentName: Global/EU-WEST
  - DH:
      type: area
      name: DH
      parentName: Global/EU-WEST/FRA
  - HQ:
      type: building
      parentName: Global/EU-WEST/FRA/DH
      name: HQ
      latitude: 50.219202
      longitude: 8.622795
      address: Horexstr 7
  - F1:
      type: floor
      name: F1
      parentName: Global/EU-WEST/FRA/DH/HQ
      rfModel: Cubes And Walled Offices
      length: 20
      width: 15
      height: 8
